server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.104.125.231:3306/vueblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity


#showSql
#logging:
#  level:
#    com:
#      example:
#        mapper : debug

logging:
  level:
    org:
      springframework:
        security: info
